226 student roster fetching
sitechtimes/regents-prep-app-frontend pull request #255
Opened 2024-12-10 16:04 UTC by AbigailLabanok

### Additions
- fetched data about students from backend and made it appear on roster page 

### Changes
- fixed styling on roster page

2024-12-11 19:58 UTC, whydoesthecodenotwork approved these changes
uhh close enough

2024-12-12 15:28 UTC, kennething requested changes

2024-12-13 15:12 UTC, bridgetf7 approved these changes

2024-12-13 15:12 UTC, merged

2024-12-13 17:45 UTC, kennething reviewed
student list doesnt get filtered when the search term is changed